version: "2"
services:
  SPAnnotationDetection:
    image: SPAnnotationDetection
    depends_on:
      - "consul"
#    ports:
#      - "8098:8090"
    environment:
      - SP_ICON_HOST=${SP_ICON_HOST}
    networks:
      spnet:

